### PR TITLE
add image moments.

### PR DESCRIPTION
**Pull request by seebacherd**
pretty big commit. image moments were added to Ops.list and the namespace was added to OpService and DefaultOpService.
the whole implementation is in the net.imagej.ops.imagemoments package and the tests are in the net.imagej.ops.imagemoments.ImageMomentsTest class.

@dietzc  do you mind taking a look? also could you format the imagemoments packages in src/main and src/test?

### CODE REVIEW

**Comment by dietzc** [comment]
:+1: looks very, very good. can be merged after:

* [ ] remove format only commits
* [ ] format code with Luna Eclipse and not Mars

**Comment by DanielSeebacher** [comment]
format only commits are removed. also it would be very nice if either you or @Squareys  could format the classes located in src/main/net/imagej/ops/imagemoments and src/test/net/imagej/ops/imagemoments.

**Comment by dietzc** [comment]
one of us will take care, thank you!

**Comment by dietzc** [comment]
one further question: are these implementations n-dimensional? if not, we should add `Contigent` to check.

**Comment by dietzc** [comment]
I formatted the code and simplified to commit message.

**Pull request merged**
