### PR TITLE
Start implementing an expression parser

### PR DESCRIPTION
**Pull request by dscho**
Please do not merge this just yet.

A couple of things are left to do, still:
- [ ] ensure that  `"a+b"` does not modify `a` (the 2-parameter "math.add" op modifies the first parameter if it is an image; I think that is fine, but we should teach the expression parser to generate a temporary image and use the 3-parameter op)
- [x] add more operators and use the [Shunting yard algorithm](https://en.wikipedia.org/wiki/Shunting-yard_algorithm) to handle operator priorities (pointed out by @ctrueden)

A few more things need to be done, but they can be done in different Pull Requests (and by people other than myself :grinning:): optimize the temporary variable usage (i.e. reuse the temporary image in "a+b*c"), and add a way to generate new ops based on entire expression (sub-)trees using Javassist (one idea is to add a hook to the `ExpressionParser.bind(map)` method that reasons over arithmetic operations by inspecting `OpExpression`s: when the op name is e.g. "math.add" and the two parameters are either a `Variable` of type `PlanarImg` or `ArrayImg` with a primitive backing store, or a to-be-introduced `JavassistedOpExpression`, generate a new `JavassistedOpExpression` based on those parameters and execute that in `OpExpression#eval()` instead.

@tinevez the idea for this Pull Request is based heavily on your Image Expression Parser, thank you so much for that!

Even if this developer was not aware of #100, this Pull Request seems to address it!

### CODE REVIEW

**Comment by dscho** [comment]
Okay, I am done with what I wanted to do (and I'll leave the problem of "a+b" modifying the first parameter to you, @ctrueden, since you already had an idea how to fix it).

**Comment by ctrueden** [comment]
Just an update on this work: we now have a much less rudimentary expression parser as [its own SciJava project](https://github.com/scijava/scijava-expression-parser). The plan is to create an `expr` op here in OPS, which leans on SJEP to do the parsing, and OPS to do the evaluation. We will still need to address the "in-place" vs. "functional" issue in the OPS framework (first bullet point in the description above). Then we'll be able to close out this issue. The conceit is then that SJEP's data structures are flexible enough for the future addition of an "OOPS" optimization layer which can do syntax tree transforms, etc.

**Comment by ctrueden** [comment]
Other thoughts and considerations for the future (maybe turn into separate issues later after this one is resolved):
* Rather than our own home baked parser, we could just use a nice scripting language like Jython. This was my original idea, which is why the README gives a Jython example after all. But we need to [overload all the Jython operators](https://docs.python.org/2/reference/datamodel.html) to "do the right thing" and call the OPS framework for evaluation.
* We could also support compiling expressions somehow for performance. That is: for a given JVM, would be nice to do the discovery of the right op(s) once, then have Java bytecode that does the actual work, instead of needing to use reflection. This consideration might improve both performance and correctness. It might even make it easier to have type-safe compile-time access to all the built-in ops, too; see also #19.

**Comment by ctrueden** [comment]
The [SciJava Expression Parser](https://github.com/scijava/scijava-expression-parser) is really polished now, and ready for `1.0.0` release. I am just validating the API a little more first, by using it in OPS.

I have pushed an [expression-parser branch](https://github.com/imagej/imagej-ops/compare/expression-parser) which uses it. There is still thought and work to be done to ensure only "pure functional" ops are used by the evaluator—i.e., `BOTH` parameters need to be handled specially (perhaps always filled with null in the case where they are optional, or perhaps not matched at all).

**Comment by ctrueden** [comment]
This work continues in PR #113.

**Pull request closed without merging**
