### PR TITLE
Refactoring of CreateKernel Ops

### PR DESCRIPTION
**Pull request by dietzc**
* Simplified hierarchy of CreateKernel ops
* Adapted namespaces and tests
* consistent namespace methods
* generalized namespaces methods to return `RAI`.

### CODE REVIEW

**Comment by ctrueden** [comment]
You're going to hate me, but I needed to make changes to these same classes as part of `create-generics`. So we'll have to reconcile things...

**Comment by dietzc** [comment]
no worries. I wait until you merged your stuff and fix the branch :+1: was not too much of work

**Comment by ctrueden** [comment]
Actually, your version basically rewrote everything, so it will be easy to fix this PR after I merge mine: probably will work to rebase with `-X theirs` to prefer your version to mine. In other words: the changes I made to the classes you have now deleted will be irrelevant.

**Comment by ctrueden** [comment]
I've got this cleaned up locally now. Testing, and if all is well, will merge.

**Comment by ctrueden** [comment]
I am guessing that this interferes even more with #375. Hopefully won't be too bad to sort out... let me know if I can help.

**Pull request merged**
