### PR TITLE
refactor LocalThresholding: use initialize

### PR DESCRIPTION
**Pull request by dietzc**
see above

### CODE REVIEW

**Comment by dietzc** [comment]
true, true and true.

**Comment by ctrueden** [comment]
I think the typing can be nicer if you do the raw cast in initialize for each of the ops, rather than keeping raw(ish) references.

**Comment by dietzc** [comment]
updated :+1: thanks!

**Comment by dietzc** [comment]
updated again

**Comment by ctrueden** [comment]
Thanks!

**Pull request merged**
