### PR TITLE
Copy Ops 

### PR DESCRIPTION
**Pull request by dietzc**
DO NOT MERGE ... but explain me why the copy tests fail?

* `ImgLabelingTest`: I don't understand why having two `Op`s with the same priorities but different input parameters are a problem.

* I don't understand the problem with `CopyTypeTest` at all.

Can you maybe help @hinerm @ctrueden?

### CODE REVIEW

**Comment by hinerm** [comment]
>Can you maybe help @hinerm @ctrueden?

@dietzc definitely! I'll look at the tests right now..

**Comment by hinerm** [comment]
>ImgLabelingTest

In the `CopyImgLabeling` op, the `conforms` method just tests whether the parameters are of [equal size and class](https://github.com/imagej/imagej-ops/blob/copy-ops/src/main/java/net/imagej/ops/copy/CopyImgLabeling.java#L79-L87) - not whether they are actually `ImgLabeling`s. So it claims to be able to support copying two equal sized `ArrayImg`s

**Comment by hinerm** [comment]
>I don't understand the problem with CopyTypeTest at all.

Exception is:

```
java.lang.IllegalAccessException: Class org.scijava.plugin.PluginInfo can not access a member of class net.imagej.ops.copy.CopyType with modifier
```

Look at the class.. it's `package` visibility. It needs to be `public`.

Also many of these plugin annotations don't conform to the `(type=Op.class, name=Ops.xyz.NAME)` standard. I updated `CopyType`.

**Comment by dietzc** [comment]
Thanks @hinerm. I overlooked the visibility of `CopyType`. Thanks for pointing me on this. However, I still don't understan the `ImgLabelingCopy` problem. My understanding of `Contigent` is that it was not introduced to match parameter types, rather than properties of the parameters. The problem in this case is, that the generic type matching of the matcher doesn't work. @ctrueden I know there were some issues with generic - type matching. Is this one of the situations where the matcher can't perform the actual matching?

**Comment by hinerm** [comment]
>However, I still don't understan the ImgLabelingCopy problem

@dietzc I dug into this more today. Looks like the actual reason both `Op` candidates are matching is that the [`DefaultConverter`](https://github.com/scijava/scijava-common/blob/scijava-common-2.43.0/src/main/java/org/scijava/convert/DefaultConverter.java#L176-L180) sees that `ImgLabeling` has a constructor that [accepts a RAI](https://github.com/imglib/imglib2-roi/blob/imglib2-roi-0.3.1/src/main/java/net/imglib2/roi/labeling/ImgLabeling.java#L85-L93) - which can therefore accept an `ArrayImg`.

So since `ArrayImgs` can be converted to `ImgLabelings` you must differentiate the `CopyImgLabeling` and `CopyArrayImg` `Op`s by priority. `CopyArrayImg` should be higher priority since it is more specific than `CopyImgLabeling`.

**Comment by dietzc** [comment]
I understand. I will fix this. Thanks! However, something is still not correct and I suspect this has a lot to do with the generic types matching. `ArrayImg`s actually can't be converted to `ImgLabeling`s in general, as only `RandomAccessibleInterval` of type `IntegerType` can be consumed by the constructor.

**Comment by hinerm** [comment]
>only RandomAccessibleInterval of type IntegerType can be consumed by the constructor

Well.. this test is using an `IntegerType` so it's reasonable. But actually the problem isn't with `CopyImgLabeling` matching, it's `CopyArrayImg` matching right?? So I think my suggestion is wrong...

**Comment by hinerm** [comment]
>So I think my suggestion is wrong... 
Nope, just kidding. I didn't realize that `CopyImgLabeling` calls copy on the underlying `Img`s during its `safeCompute` method.

I do not think this is a problem with generic matching because if you have an `ImgLabeling` that you want to copy, then you necessarily have an `RAI<? extends IntegerType>` as the index img of the labeling. So you can always construct an `ImgLabeling` from this `RAI`, whether or not the `RAI` is also an `ArrayImg` or not (as it happens to be in this case).

The point is, you ***must*** have a higher priority `Copy Op` that can convert between `RAI`s, or the `CopyImgLabeling` will recurse infinitely.

**Comment by ctrueden** [comment]
Note that issue #103 is relevant here: we would have fewer op clashes (and no clash here in particular) if the matcher preferred ops which do not require calls to the `ConvertService` to fulfill.

**Comment by dietzc** [comment]
not ready for merge, yet. however, getting close.

**Comment by dietzc** [comment]
@tibuch can you also take care about this? I think only tests and a few more specialized copy ops are missing in a first step.

**Comment by dietzc** [comment]
I forced push several changes and `FIXME`s. which we should discuss at the hackathon (general questions). Afterwards, we (@tibuch) only need(s) to add more tests and we can merge.

* [ ] Add tests.

**Comment by dietzc** [comment]
@ctrueden  @hinerm if you could do a quick review... I think we can merge then.

**Comment by hinerm** [comment]
- [ ] @dietzc my understanding is that namespaces should have a [varargs](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.20.0/src/main/java/net/imagej/ops/math/MathNamespace.java#L63) signature for each built-in method.. @ctrueden maybe that should be covered in the signature test..?

- [ ] Tests don't have licenses. Need a `mvn license:update-file-header` pass.

- [ ] Style and whitespace stuff. Could just use a [style cleanup](https://github.com/imagej/imagej/tree/imagej-2.0.0-rc-39/config) pass.

- [ ] Needs manual reconciliation with `master`. Just need to union the `OpService` and `DefaultOpService` changes.

**Comment by dietzc** [comment]
>  @dietzc my understanding is that namespaces should have a varargs signature for each built-in method.. @ctrueden maybe that should be covered in the signature test..?

I wouldn't do a varargs for every `Copy` implementation and as the `Copy` interface is not an `Op`, we can't do it for it.

**Comment by dietzc** [comment]
I forgot to push the changes I did some days ago ;-) No it should be reviewable!

**Comment by dietzc** [comment]
@tibuch did you force push? My changes are gone...

**Comment by dietzc** [comment]
closed in favour of https://github.com/imagej/imagej-ops/pull/235

**Pull request closed without merging**
