### PR TITLE
Make op method extensible

### PR DESCRIPTION
**Pull request by LeonYang5114**
See #176 for the discussion.
Filter and logic namespaces are not included in this refactoring, since that involves more intricate refactoring. They will be done separately.

Since this refactoring reveals some bugs, bug fixes are included in this branch for convenience.

### CODE REVIEW

**Comment by dietzc** [comment]
shouldn't this work also comprise cleaning up methods like https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/copy/CopyNamespace.java#L89, as this case is covered for example by https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/copy/CopyNamespace.java#L126 (the `OpMatcher` will find the `CopyArrayImg` as the op with the highest priority if the passed `IterableInterval`s are actually `ArrayImg`s.

**Comment by ctrueden** [comment]
@dietzc I agree that that is the next step, yeah. But let's get this merged first, then do another PR for that ASAP.

**Comment by dietzc** [comment]
Ok.makes sense.

**Comment by dietzc** [comment]
looks good to me. @LeonYang5114 tests passing? anything else you want to work on before merging? @ctrueden OK with merging?

**Comment by ctrueden** [comment]
[256px-smirc-thumbsup svg](https://commons.wikimedia.org/wiki/File:SMirC-thumbsup.svg)

**Pull request merged**
