### PR TITLE
MapNeighborhood: Generalize output type to IterableInterval

### PR DESCRIPTION
**Pull request by dietzc**
see title

### CODE REVIEW

**Comment by stelfrich** [comment]
@dietzc Conflicts resolved and tests are passing. Looks good to me.

**Comment by dietzc** [comment]
@stelfrich can you do a rebase of this branch with master instead of a "merge"? would be awesome

**Comment by stelfrich** [comment]
> @stelfrich can you do a rebase of this branch with master instead of a "merge"? would be awesome

Done. Tests passing.

**Comment by dietzc** [comment]
now I'm one of the cool kids merging their own branch :+1:

**Comment by stelfrich** [comment]
At least you had someone else take a look at it..  :dancers:

**Pull request merged**
