### PR TITLE
Fitting ellipse to point set

### PR DESCRIPTION
**Pull request by tibuch**
I implemented and tested a fitting ellipse implementation https://github.com/imagej/imagej-ops/issues/452.

I verified the results with the matlab-implementation from http://research.microsoft.com/en-us/um/people/awf/ellipse/ellipse-pami.pdf.

@ctrueden or @dietzc  could you check the copyright notice? https://github.com/imagej/imagej-ops/blob/fittingEllipseToPointSet/src/main/java/net/imagej/ops/geom/geom2d/DefaultFittingEllipse.java#L24

PS: All tests are passing :)

### CODE REVIEW

**Comment by tpietzsch** [comment]
> I verified the results with the matlab-implementation from http://research.microsoft.com/en-us/um/people/awf/ellipse/.
That link doesn't lead to ellipse fitting description, just to awf's homepage. Can you please add a link to the paper/description?

@dietzc  @tibuch I have somewhere a `HyperEllipsoid` and fitting that to noisy point clouds. It has 
 * a method of fitting a hyper-ellipsoid to points I adapted from BoneJ (who adapted it from a Matlab script). It uses algebraic distance instead of geometric, so it doesn't handle noise very well, but with enough points it seems rather accurate.
 * computing the shortest (i.e., perpendicular) distance from a point to a (hyper-)ellipsoid (adapted from a C++ implementation). This is a surprisingly difficult problem, and an iterative solution.
 * RANSAC-like random sampling using the above things to robustly fit an a (hyper-)ellipsoid to a noisy point cloud with outliers.

See this forum discussion http://forum.imagej.net/t/licensing-question-for-imglib-algorithm-addition/1255 and this imglib-algorithm branch https://github.com/imglib/imglib2-algorithm/compare/ellipsoid-fitting

It would be good if we could put this into imglib2 somewhere. I wouldn't put it into `roi` probably.
A `HyperEllipsoid` is not a ROI, just the mathematical object. (You can make a ROI from it very easily though, it's a borderline case...)

**Comment by tibuch** [comment]
@tpietzsch changed the link: http://research.microsoft.com/en-us/um/people/awf/ellipse/ellipse-pami.pdf

**Comment by tpietzsch** [comment]
> @tpietzsch changed the link: http://research.microsoft.com/en-us/um/people/awf/ellipse/ellipse-pami.pdf

That still doesn't work for me!?

**Comment by tibuch** [comment]
@tpietzsch strange. this one: https://pdfs.semanticscholar.org/090d/25f94cb021bdd3400a2f547f989a6a5e07ec.pdf

**Comment by tpietzsch** [comment]
@tibuch thank you

**Comment by tibuch** [comment]
@tpietzsch I am trying to verify all features of ops https://github.com/imagej/imagej-ops/issues/449 and I couldn't find reference numbers for the Major-Minor-Axis features. That's why I ended up implementing fitting ellipse. 

But I am happy to use your `HyperEllipsoid`.

**Comment by tpietzsch** [comment]
Hmm, what are you actually trying to do? The geom2d feature stuff reads as if you are trying to find the smallest (area?) ellipse containing all the points? That is different from fitting an ellipse to a set of points, for example in the sense of: find the ellipse that minimizes mean squared distance from points to the ellipse.

**Comment by tibuch** [comment]
> Hmm, what are you actually trying to do?
I try to find a more generic description of a shape in form of an ellipse. 

> The geom2d feature stuff reads as if you are trying to find the smallest (area?) ellipse containing all the points?
As far as I understand the current major-minor-axis implementation:
The best fitting ellipse is the ellipse with the "same" area as the polygon. In the code this paper is referenced: http://www.sciencedirect.com/science/article/pii/S0191814103000932

> That is different from fitting an ellipse to a set of points
It is different, but I think as long as it describes the shape (which could be a Polygon, IterableInterval or PointCollection) it works.

The reason why I am looking for a different implementation is to decouple the fitting ellipse implementation from the major-minor-axis implementation and to verify the numbers against other known implementations.

**Comment by tibuch** [comment]
I guess this PR can be closed. The fitting ellipse implementation used in minor-major-axis computations is correct as far as I know and I was able to verify all geometric 2D features. 

> The geom2d feature stuff reads as if you are trying to find the smallest (area?) ellipse containing all the points?

This is true and this implementation does not do that.

**Pull request closed without merging**
