### PR TITLE
Create extended rai

### PR DESCRIPTION
**Pull request by LeonYang5114**
Wrapper of a `link RandomAccessibleInterval` and a `OutOfBoundsFactory` that keeps the interval information. All the method except for accessing out of bounds data are handled by the source RAI. Notice that this class is very similar to [`ExtendedRandomAccessibleInterval`](https://github.com/imglib/imglib2/blob/master/src/main/java/net/imglib2/view/ExtendedRandomAccessibleInterval.java), which does not have the interval information.

Creating an instance of this class could be considered a shorthand for: `Views.interval(Views.extend(source, outOfBoundsFactory), source);`

This branch is experimental. Any comment would be appreciated.

### CODE REVIEW

**Comment by bnorthan** [comment]
@LeonYang5114 feel free to also refactor [```ConvolveNaive```](refactor https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/filter/convolve/ConvolveNaive.java) as part of this.  I will just take your version.

**Comment by dietzc** [comment]
isn't this a duplicate of the efforts in: https://github.com/imagej/imagej-ops/tree/views?

**Comment by LeonYang5114** [comment]
I did not notice that we have that branch. But as I read some of the code, I think that's probably not duplicate efforts. What I am doing here is to make `ExtendedRandomAccessibleInterval` easier to use. The new class `ExtendedRAI` is exactly the same as `ExtendedRandomAccessibleInterval` except that it keeps the `Interval` information, so that we can typed on `ExtendedRAI` in an op to make `RAI` extension really _required_. I did not see similar logic in the branch you mentioned. Hope that makes sense.

**Comment by dietzc** [comment]
Are you sure that we want to introduce `ExtenededRAI` on our side just for convenience reasons? We can have an `Op` in the aforementoined `views` branch which actually does `Views.interval(Views.extend(source, outOfBoundsFactory), source)`. Having a class `ExtendedRAI` doesn't really make sense, as also the optimizations within the `Views` logic would fail. In short: I'm against adding `ExtendedRAI` but certainly we should have an `Op` which encapsulates `Views.interval(Views.extend(source, outOfBoundsFactory), source)` in https://github.com/imagej/imagej-ops/tree/views. Can you make this happen @tibuch?

**Comment by ctrueden** [comment]
@dietzc @tpietzsch What if the `ExtendedRandomAccessibleInterval` was still an `Interval`? That would solve our issue. Is there some harm in doing that?

**Comment by dietzc** [comment]
`ExtendedRandomAccessibleInterval` can't be an `Interval` as it is defined in infinity. however, I opened a PR https://github.com/imglib/imglib2/pull/123 which I'm sure will trigger some discussions. Anyway, I vote _strongly_ against having any `ExtendedRAI` class or any other data-structure within ops which actually should live in `imglib2`. We may not diverge from `imglib2`s principles, rather we should just use them.

I will close this PR. If my PR at `imglib2`will not be accepted we will find another solution.

**Pull request closed without merging**
