### PR TITLE
Image moment calculation edits

### PR DESCRIPTION
**Pull request by djniles**
Found some discrepancies in image moment calcs HuMoment2 (sign change in equation) and the normalized central moments (integer division of exponent). Remaining discrepancies were due to Matlab numerical error.

### CODE REVIEW

**Comment by ctrueden** [comment]
@djniles Awesome, thank you very much for following up with this!

@seebacherd Here's the PR [mentioned on the forum](http://forum.imagej.net/t/imagemoments-in-imagej-ops-potential-miscalculations/521).

**Comment by dietzc** [comment]
are the unit tests still passing?

**Comment by djniles** [comment]
@dietzc It looks like previously the unit tests had been passing because an absolute tolerance of 1e-3 was used for expected numbers 1e-11 or smaller.  If I changed the tolerance to be relative instead of absolute (i.e., 1e-14 for an expected value of ~1e-11) Hu moments 2-7 all failed the unit tests prior to the corrections.  After making the corrections, all of the moments passed the unit tests with 1e-3 relative tolerance.

**Comment by dietzc** [comment]
@seebacherd can you review this PR and find a better test image?

**Comment by seebacherd** [comment]
Unfortunately I can neither commit to this PR here or directly in djniles project. I've calculated the Image Moment values with OpenCV for the following image:

lenna

And also updated the tests to use the new values:

[ImageMomentsTest.txt](https://github.com/imagej/imagej-ops/files/65582/ImageMomentsTest.txt)


But there still seem to be some differences between the OpenCV values and our implementation.

**Comment by ctrueden** [comment]
> Unfortunately I can neither commit to this PR here or directly in djniles project.

@seebacherd What you can do is branch from the PR, do your extra commits (and/or rewrite the existing commits), and then push that new branch.

**Comment by dietzc** [comment]
So, how to proceed?

**Comment by ctrueden** [comment]
Did @seebacherd create his own branch with updates? If so, he can file a new PR that supercedes this one.

**Comment by djniles** [comment]
For what it's worth, here are my numbers for Lena using Matlab.  I also include my code for calculating the moments.  It looks like a couple of the moments (5 and 7) disagree by quite a bit, but I'm not sure why.

https://gist.github.com/djniles/ee00f9dc54fc32e906a1

**Comment by ctrueden** [comment]
@tibuch What is the status of this branch? Does the work continue elsewhere? I am confused...

**Comment by tibuch** [comment]
Thanks @djniles for the bugfix! I just updated the test-values and set the test-epsilon to 10e-8. 

I opened another PR with my additional commit: https://github.com/imagej/imagej-ops/pull/491

**Pull request closed without merging**
