### PR TITLE
Integral images

### PR DESCRIPTION
**Pull request by stelfrich**
(Re)Implementation of [integral images](https://en.wikipedia.org/wiki/Summed_area_table) inspired by [`IntegralImg`](https://github.com/imglib/imglib2-algorithm/blob/9455b45fdb361227ccbacde538b22cef27b1ee05/src/main/java/net/imglib2/algorithm/integral/IntegralImg.java) from imglib2-algorithm (for which a wrapper is provided).

See #331.

### CODE REVIEW

**Comment by dietzc** [comment]
* Make it a `HybridCF`, such that users can pass whatever they want in the `compute1` as output
* Don't restrict yourself to `DoubleType' as output. Could be any numeric type.
* `FunctionOp` can assume `DoubleType` or `LongType` as output (depending on input)

**Comment by stelfrich** [comment]
@dietzc I have addressed the points in the last commit.

**Comment by dietzc** [comment]
is the title "Do Not Merge" still valid?

**Comment by stelfrich** [comment]
There is still some tests failing because of namespace confusion that I can't wrap my head around:

```
Running net.imagej.ops.image.ImageNamespaceTest
[ERROR] Mismatched inputs:
	op = net.imagej.ops.image.integral.DefaultIntegralImg
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.image.ImageNamespace.integral(net.imglib2.RandomAccessibleInterval,int)```

**Comment by stelfrich** [comment]
I dug a little into that error. The problem seems to be the [`DefaultOpMatchingService.padArgs()`](https://github.com/imagej/imagej-ops/blob/43074652368c1e4335ce666f9f6331d1142a2d40/src/main/java/net/imagej/ops/DefaultOpMatchingService.java#L174-L214) that fills up missing arguments from right to left to test if a candidate matches the parameters. In case of a `UnaryHybridCF` with optional parameters that might be a problem:
```
(RandomAccessibleInterval out?) =
	net.imagej.ops.image.integral.DefaultIntegralImg(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in,
		int order?)
```
The arguments would have to be padded from both sides to check for matching candidates? Does that sound reasonable, @dietzc, @ctrueden?

**Comment by dietzc** [comment]
actually, this shouldn't be a problem. Can you post the complete error message (or is it complete?).

**Comment by stelfrich** [comment]
I had stripped the uninteresting parts, @dietzc. Here is the complete log:

```
Running net.imagej.ops.image.ImageNamespaceTest
[ERROR] Mismatched inputs:
	op = net.imagej.ops.image.integral.DefaultIntegralImg
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.image.ImageNamespace.integral(net.imglib2.RandomAccessibleInterval,int)
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.067 sec <<< FAILURE! - in net.imagej.ops.image.ImageNamespaceTest
testCompleteness(net.imagej.ops.image.ImageNamespaceTest)  Time elapsed: 0.066 sec  <<< FAILURE!
java.lang.AssertionError: Coverage mismatch
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at net.imagej.ops.AbstractNamespaceTest.assertComplete(AbstractNamespaceTest.java:81)
	at net.imagej.ops.image.ImageNamespaceTest.testCompleteness(ImageNamespaceTest.java:51)
```

**Comment by stelfrich** [comment]
It boils down to [`DefaultOpMatchingService.java#L309`](https://github.com/imagej/imagej-ops/blob/43074652368c1e4335ce666f9f6331d1142a2d40/src/main/java/net/imagej/ops/DefaultOpMatchingService.java#L309) where the padded arguments `[interface net.imglib2.RandomAccessibleInterval, int, null]` do not match the candidate:
```
(RandomAccessibleInterval out?) =
	net.imagej.ops.image.integral.DefaultIntegralImg(
		RandomAccessibleInterval out?,
		RandomAccessibleInterval in,
		int order?)
```
Removing the method with the conflicting signature makes the test pass but then the `Function` part of `DefaultIntegralImg` can't be used with the optional parameter set.

**Comment by stelfrich** [comment]
I have opened an issue (#379) for further discussions on the completeness of a namespace / matching of `HybridCF`s with optional parameters.

**Pull request merged**
