### PR TITLE
Improve varargs matching

### PR DESCRIPTION
**Pull request by hinerm**
Add logic to handle the case where varargs may be split out into individual arguments, instead of aggregated in an array.

### CODE REVIEW

**Comment by hinerm** [comment]
@ctrueden since you love reviewing PRs so much, would you mind signing off on this?

**Comment by ctrueden** [comment]
@hinerm and I talked for quite a while about how best to handle varargs in OPS. The issue with this PR's approach is that it only collapses tail elements with identical types. So it solves the `createimg` case where you give a list of `int` values and want it transformed into an `int[]` argument. But it does not solve mixed type cases, such as passing an `ArrayImg` and a `PlanarImg` and expecting it to match an op with its last parameter being `Img[]`. And solving the mixed type case is much more involved, especially when combined with the OPS framework's existing matching of optional parameters—the current approach of padding parameters to fill nulls would no longer be sufficient to handle varargs too.

As such, we agreed to close this PR, in favor of pursuing the built-ins work (#19). @hinerm is going to add all the `createimg` built-in signatures in a separate PR, which definitely solves the issue [recently discussed on imagej-devel](http://imagej.net/pipermail/imagej-devel/2015-April/002560.html). And in general, the built-ins approach solves varargs for all built-in ops.

What it does not provide is a fully dynamic (i.e., extensible) varargs solution for ops outside the core imagej-ops component. We could file a separate issue to tackle that at some point in the future, though from my perspective, it is very low priority. The vast majority of scripts will be calling into the `OpService` built-in methods—and furthermore, any third-party extensions can provide their own service class that similarly provides built-in type-safe method signatures. They could even reuse the forthcoming utility code for unit testing that all built-in methods are indeed present and type compatible.

**Comment by ctrueden** [comment]
One potentially slick way of providing fully dynamic varargs would be in conjunction with op reducers (#57). It would be possible to create a general op reducer that effectively does the second "pass" this PR did, to look for matching signatures with collapsed arguments.

**Comment by hinerm** [comment]
Note that the issue this PR set out to address (`createimg(int, int)` not matching) is now resolved by https://github.com/imagej/imagej-ops/commit/f96f76692577c38444e51bdf4c1b7264f2611f06

**Comment by ctrueden** [comment]
OK, so I stupidly reviewed part of this again. Sorry for the noise. At least my new comments are reasonable!

**Pull request closed without merging**
