### PR TITLE
Thinning from Knime/Knip

### PR DESCRIPTION
**Pull request by kephale**
Here is the thinning code we'd talked about in gitter. It seems to be working with minimal modification.

Note, the Knime copyright info remains.

### CODE REVIEW

**Comment by dietzc** [comment]
@kephale sorry that this takes so long for review. I will give me best to get it done this week

**Comment by kephale** [comment]
No worries. Give me a shout if you think anything else needs to be done.

**Comment by ctrueden** [comment]
Looks like there is a licensing issue: the code you adapted is [GPL](http://imagej.net/GPL). But ImageJ Ops is licensed under [BSD-2](http://imagej.net/BSD-2).

Do we have permission from the KNIME authors to relicense this?

If not, it will need to go into a separate component.

**Comment by kephale** [comment]
That is what I was wondering about. @dietzc said something that made it seem like this sort of code from KNIME was fair game for adding to imagej-ops.

**Comment by gab1one** [comment]
@kephale a few points to improve this PR:
- [ ] Change the license in each file to BSD, this should be no problem as we want as many KNIP algorithms in Ops as possible.
- [ ] The code does use the current API as it was written before ImageJ-Ops, it needs to be adapted to become a proper op. This entails:
    - [ ] Inheriting from the correct Op / Computer /...   supertype
    - [ ] ``@Parameter`` annotations for member injection
    - etc.
- [ ] Add default methods calling the ops to a namespace (if no fitting one exists add one), making them easy to discover and call.

**Comment by kephale** [comment]
Closed and moved to https://github.com/imagej/imagej-ops/pull/317

**Pull request closed without merging**
