### PR TITLE
Enhance logic

### PR DESCRIPTION
**Pull request by LeonYang5114**
Create the Conditional interface and two of its implements, If and Default. They might be useful when working with thresholded images and using eval Op.

See discussion in #263

### CODE REVIEW

**Comment by ctrueden** [comment]
@LeonYang5114 Can you please rebase this over the latest master so that it can merge?

**Comment by LeonYang5114** [comment]
@ctrueden Thanks for the reminder

**Comment by LeonYang5114** [comment]
@ctrueden this branch is now up-to-date. However, I am not able to improve other condition ops, as they are actually not "operator"s, but building blocks of the conditions. Tell me if you have any idea.

**Comment by ctrueden** [comment]
> Tell me if you have any idea.

Probably we should make the package as a whole less convoluted. We need `greaterThan`, `lessThan`, etc. ops that actually work intuitively, after all.

Also, the `conditional` op should declare `if` as an alias, so that you can write e.g. `if(equal(a, b), c, d)` in an `eval` statement. This is a simple change to `Ops.list`.

**Pull request merged**
