### PR TITLE
Introduce patterns for chaining ops

### PR DESCRIPTION
**Pull request by ctrueden**
This is the fruit of my hackathon-related efforts:

* Every op now knows its environment, and environment is fully baked.
* All ops extend the common AbstractOp base class.
* Special ops (computers and functions) implement a common interface.
* New methods to limit matching to desired special ops.
* Duck-type Initializable interface for ops which need to set up.
* Support for matching ops based on multiple types, and output types.
* Better error messages when op types don't match.
* Better validation and error checking upon op creation.
* Improve conciseness/convenience of a few APIs.
* And of course: lots of code cleanup and warning fixes.

### CODE REVIEW

**Comment by ctrueden** [comment]
In the style of the cool kids today, I merge my own PR before anyone comments!

Don't worry: I tested this thoroughly—all commits build with passing tests.

**Comment by ctrueden** [comment]
@dietzc The next branch is called `special-types`, and has the start of the `inType()` and `outType()` accessors, as well as the start of cleanup for the `create` namespace as per #160—this cleanup will be needed now, to address issues with `outType()`.

**Comment by dietzc** [comment]
> In the style of the cool kids today, I merge my own PR before anyone comments!

:+1:  fantastic curtis. thanks

**Comment by bnorthan** [comment]
+2! Thanks Curtis.  Sounds like this will be helpful for iterable algorithms like Richardson Lucy as well.

**Pull request merged**
