### PR TITLE
Linear and Non linear filters

### PR DESCRIPTION
**Pull request by Squareys**
Hello everybody, hello @dietzc !

Since #169 was finally merged, here is another pull request based upon that work.
This PR implements the following:
 - Max filter
 - Mean filter
 - Median filter
 - Min filter
 - Variance filter

TODO:
  - [x] Tests
  - [x] Sigma filter
  - [x] Op methods

### CODE REVIEW

**Comment by dietzc** [comment]
I changed the title to "Linear and ..." filters as `MeanFilter` is part of this PR. Anyway, it seems like parts of https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/filter/convolve/ConvolveNaive.java can be replaced with your implementation @Squareys?

**Comment by Squareys** [comment]
@dietzc Yeah, well, it never came to me that you could reverse the Mean filter.

This is ready for merge now :)

**Comment by dietzc** [comment]
awesome. thanks.

**Comment by LeeKamentsky** [comment]
Re the mean filter on a rectangle implemented as a kernel of 1/m/n: it's seperable (see http://blogs.mathworks.com/steve/2006/11/28/separable-convolution-part-2/ for how to detect a separable filter and reduce it to a chain of 1D convolutions). That means it runs in m+n instead of m*n. An improvement to ConvolveNaive would be to check for separability. N-D Gaussian filters are seperable and traditionally implemented as a chain of 1D filters.

**Comment by dietzc** [comment]
@LeeKamentsky I didn't know that a `MeanFilter` isn't separable, but it makes sense of course. You think we should move it to non-linear category then? 

All separable filters can be applied using `SeperableSymmetricConvolution` of imglib2. However, finding out if a filter is seperable isn't easy (numerical reasons make the test inexakt).

**Comment by LeeKamentsky** [comment]
Mean is linear and seperable if calculated on a rectangle (but not separable if calculated on a circle). I think the roundoff error for the singular value decomposition is 2 * eps * max(dims) where eps is the difference between the mean of the kernel in your floating point representation and the next floating point number  that is larger than it. So if you have an SVD function, it's "easy" (by which I mean possible, given a whole lot of effort).

**Comment by dietzc** [comment]
> Mean is linear and seperable if calculated on a rectangle (but not separable if calculated on a circle).

Makes sense, yes.

> I think the roundoff error for the singular value decomposition is 2 * eps * max(dims) where eps is the difference between the mean of the kernel in your floating point representation and the next floating point number that is larger than it. So if you have an SVD function, it's "easy" (by which I mean possible, given a whole lot of effort).

Thank you. I always had the numerical problem here and didn't know how to solve it.

**Pull request merged**
