### PR TITLE
Rework the design of the function type hierarchies

### PR DESCRIPTION
**Pull request by ctrueden**
As discussed in issue #149, the idea of a "function" was not quite intuitive from a mathematical perspective: its `compute(I, O)` method allowed (or sometimes required) passing a preallocated output object, into which the function result would be stored. This is not pure functional programming, but instead a hybrid approach making both stateful/in-place and functional paradigms possible.

This branch establishes four core op interfaces, from which most ops derive:
* `ComputerOp`, which defines `void compute(I, O)` (formerly `Function`)
* `FunctionOp`, which defines `O compute(I)` (formerly `Computer`)
* `HybridOp`, which extends both `ComputerOp` and `FunctionOp`, and adds an `O createOutput(I)` method (formerly `OutputFunction`)
* `InplaceOp`, which extends `ComputerOp` and defines `compute(A)` (formerly `InplaceFunction`)

And it provides an abstract base class for each of these interfaces.

With these changes, it is no longer allowed to pass `null` to `compute(I, O)` for the output reference; if you need that, use `HybridOp` and call `compute(I)` instead.

The branch also renames API and variables as appropriate to reflect this change.

Lastly, the branch contains many miscellaneous changes of various sorts, performed while working on the refactoring.

### CODE REVIEW

**Comment by ctrueden** [comment]
@dietzc @hinerm I am now super happy with this work, and will merge tomorrow, but if you want to do a quick review in the meantime, that would be welcome! (Though I'm not sure how "quick" it is possible to be when reviewing ~50 commits...)

**Comment by dietzc** [comment]
First of all: Thank you very much @ctrueden. I think this refactoring will _really_ help us and others understanding the concepts and API of Ops much better. I will review as much as possible today

Question 1: 
> FunctionOp, which defines O compute(I) (formerly Computer)
> HybridOp, which extends both ComputerOp and FunctionOp, and adds an O createOutput(I) method (formerly OutputFunction)

`FunctionOp` itself can already have the `O createOutput(I)` as it has to create an output, too?

**Comment by ctrueden** [comment]
> `FunctionOp` itself can already have the `O createOutput(I)` as it has to create an output, too?

Sure, that would be OK! Note that I didn't think hard about incorporating your buffer factory stuff into the core design (yet), but if you have ideas there, I'm happy to discuss. I see that as an additional change on top of this redesign, though.

**Comment by ctrueden** [comment]
One reason for `FunctionOp` not to have `createOutput` is for simplicity. We have two options in order to move it upstream that way:

1. Force every `FunctionOp` implementation to implement both methods (adds complexity).
2. Put a default `createOutput` implementation in `AbstractFunctionOp`, which simply does `return compute(I);` (will make many functions in practice do extra computation work when they are only supposed to be creating an output)

So my thinking on this is that we should instead focus on polishing the buffer factory idea a bit, and somehow work that in. Composition preferred to inheritance and all that.

**Comment by dietzc** [comment]
The `BufferFactory` idea is just used for `Loop`s, right? I don't think we need  this concept in general, or do youthink its really useful?

**Comment by dietzc** [comment]
> Put a default createOutput implementation in AbstractFunctionOp, which simply does return compute(I); (will make many functions in practice do extra computation work when they are only supposed to be creating an output) 

I wouldn't do that. this is really something where users of the library can do really bad things ....

**Comment by ctrueden** [comment]
> The `BufferFactory` idea is just used for `Loop`s, right?

Right now, yes.

> I don't think we need  this concept in general, or do youthink its really useful?

It seems generalizable to me, but I am not sure. Like I said, I didn't think about it too much yet, it's just an intuition. My current idea is actually that the `createOutput` implementations for `HybridOp`s could lean on `ops.create().foo(...)` calls instead of using a special new type hierarchy. Then we could maybe even get rid of `BufferFactory` altogether.

**Comment by ctrueden** [comment]
> I wouldn't do that. this is really something where users of the library can do really bad things ....

Agreed. So if you are OK with it, I'd like to simply leave `createOutput` in `HybridOp` and not `FunctionOp`. I feel like it makes functions unnecessarily complex otherwise.

**Comment by dietzc** [comment]
> My current idea is actually that the createOutput implementations for HybridOps could lean on ops.create().foo(...) calls instead of using a special new type hierarchy. Then we could maybe even get rid of BufferFactory altogether. The CreateImgFromImg op is a perfect example of this.

This should definitively be the case, yes. However, in some situation you can't simply use `CreateImgFromImg` as you need more dedicated settings (e.g. projections require images with one dimension less).

The cool thing about the `BufferFactory` is, that you can reuse objects... (e.g. while looping your don't have to create one object after the other, just circulate three objects in total).

**Comment by dietzc** [comment]
anyway, I think this work is great and from my side it would be great if you would merge this branch. We can fix thing we overlooked now in the next few weeks or at the hackathon, as many thing just pop up during daily work with the library.

**Comment by ctrueden** [comment]
Thanks for taking the time to look it over!

**Pull request merged**
