### PR TITLE
Gauss implementation for non-interval RA input

### PR DESCRIPTION
**Pull request by axtimwalde**
* added Gauss implementation for non-interval RA input
* reduced type specifity of Gauss Ops to NumericType

### CODE REVIEW

**Comment by ctrueden** [comment]
@axtimwalde Are you still working on this? Or are you looking for assistance on getting the build to pass? What is the status?

**Comment by axtimwalde** [comment]
@ctrueden the test fails because of a, to me, mysterious coverage error.  I asked some questions but did not understand yet what I am expected to do.  The test asks me to implement a method that does not make sense: one that creates an output although the implemented Op is a C, not a CF.

**Comment by ctrueden** [comment]
Extending `AbstractUnaryHybridC` class directly makes no sense—that abstract class exists only as a common layer for `AbstractUnaryHybridCI` and `AbstractUnaryHybridCF`. If your goal was for `DefaultGaussRA` to simply be a computer, then change it to extend `AbstractUnaryComputer` instead, and the tests will pass.

**Comment by axtimwalde** [comment]
@ctrueden the tests are finally passing, if you have no further objections, it would be great if this could be merged (or better rebased and squashed I guess).

**Comment by ctrueden** [comment]
I cleaned up the commits, but haven't had time to 100% finalize it yet. Will do so as soon as I can. In the meantime, let me know if you don't like what you see.

**Comment by axtimwalde** [comment]
@ctrueden thanks!  I do not have preferences regarding style.  Most of what you changed was there before this pull request and I tried to comply.

**Comment by ctrueden** [comment]
It is done!

**Comment by axtimwalde** [comment]
Thanks @ctrueden!

**Pull request merged**
