### PR TITLE
PR: Haralick Features

### PR DESCRIPTION
**Pull request by dietzc**
### NOT MEANT TO BE MERGED, YET ###

Missing:
* [ ] Quick review
* [ ] Question: Are "nested" namespaces supported?
* [ ] Add/Finalize test (since now only a test was added to demonstrate API usage)

@ctrueden I started implementing a much simpler version of features. To illustrate the idea I implemented the so called Haralick-Features. The main idea is: I cache the results of a `op.run(...)` within a special `FeatureOpService`. In the case of features, we don't even need a very smart cache, as the results of the computation have to fit in memory anyway. However, we can simply delete this `FeatureOpService` as soon as the `DefaultOpService` supports caching and nearly no code will change (besides the code e.g. in the `HaralickFeatureSet`, where we have to remove the `FeatureOpService`). Like this I was also able to provide a very nice API in the `HaralickNamespace` such that features can be calculated individually. Again, as soon as `OpService` supports caching, even the evaluation of these features will be smart and redundant computations are avoided implicitly. 

Does this make sense? If you like the idea/workaround I will add _all_ other features as soon as possible!

Christian

### CODE REVIEW

**Comment by ctrueden** [comment]
Regarding nested namespaces: Do we really need them? Really? It complicates things even further... but they could conceivably be added.

What were you thinking? Maybe we can come up with a nice single-layer naming scheme.

**Comment by ctrueden** [comment]
I didn't review everything thoroughly, but I wrote some comments. All in all, this looks awesome. It does seem that most of the code will not need to be updated at all in response to a chance in how caching works.

So: fix what you want in response to my comments above, then feel free to merge. The only thing I have a real substantial opinion about is the `OpService` override—I think a `FeatureOpService` that has an `OpService` might be better unless there is some reason it fundamentally can't work.

**Comment by dietzc** [comment]
> Regarding nested namespaces: Do we really need them? Really? It complicates things even further... but they could conceivably be added. What were you thinking? Maybe we can come up with a nice single-layer naming scheme.

I was wondering if we should collect all the feature implementations in `ops.feature.xy`, as there will be many (> 8) of them.

**Comment by dietzc** [comment]
I cleaned up the branch a bit!

**Comment by ctrueden** [comment]
> I was wondering if we should collect all the feature implementations in `ops.feature.xy`, as there will be many (> 8) of them.

Can you give an example? You mean that `xy` would be a subnamespace, right? Not merely a feature computation op for a feature named `xy`?

**Comment by dietzc** [comment]
For example,  we do have several semantically different features/measurements/descriptors:

* `ops().stats().*`
* `ops().haralick().*`
* `ops().geometric().*`
* `ops().imagemoments().*`
* `ops().tamura().*`
* `ops().localbinarypatterns().*`
* `ops().shape().*`
* `ops().zernike().*`
* `ops()....().*`

More can easily be added in the future. that's why I was asking about:


* `ops().features().stats().*`
* `ops().features().haralick().*`
* `ops().features().geometric().*`
* `ops().features().imagemoments().*`
* `ops().features().tamura().*`
* `ops().features().localbinarypatterns().*`
* `ops().features().shape().*`
* `ops().features().zernike().*`
* `ops().features()....().*`

**Pull request merged**
