### PR TITLE
Fix README's example, once and for all

### PR DESCRIPTION
**Pull request by dscho**
When running `UsingOps`, the user is greeted thusly:

```
[INFO] Found 199 ops
[INFO] Available operations:
	[111.0] (net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image) = net.imagej.ops.arithmetic.add.parallel.AddConstantToArrayDoubleImageP(net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image, byte value)
	[110.0] (net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.ByteType, net.imglib2.img.basictypeaccess.array.ByteArray> image) = net.imagej.ops.arithmetic.add.parallel.AddConstantToArrayByteImageP(net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.ByteType, net.imglib2.img.basictypeaccess.array.ByteArray> image, byte value)
	[101.0] (net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image) = net.imagej.ops.arithmetic.add.AddConstantToArrayDoubleImage(net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image, double value)
	[100.0] (net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.ByteType, net.imglib2.img.basictypeaccess.array.ByteArray> image) = net.imagej.ops.arithmetic.add.AddConstantToArrayByteImage(net.imglib2.img.array.ArrayImg<net.imglib2.type.numeric.integer.ByteType, net.imglib2.img.basictypeaccess.array.ByteArray> image, byte value)
	[100.0] (java.lang.Object result) = net.imagej.ops.onthefly.ArithmeticOp$AddOp(java.lang.Object result, java.lang.Object a, java.lang.Object b)
	[0.6] (double a) = net.imagej.ops.arithmetic.add.AddConstantToDouble(double a, double b)
	[0.5] (long a) = net.imagej.ops.arithmetic.add.AddConstantToLong(long a, long b)
	[0.4] (float a) = net.imagej.ops.arithmetic.add.AddConstantToFloat(float a, float b)
	[0.3] (int a) = net.imagej.ops.arithmetic.add.AddConstantToInteger(int a, int b)
	[0.2] (short a) = net.imagej.ops.arithmetic.add.AddConstantToShort(short a, short b)
	[0.1] (byte a) = net.imagej.ops.arithmetic.add.AddConstantToByte(byte a, byte b)
	[0.0] (net.imglib2.IterableRealInterval<capture of ?> image) = net.imagej.ops.arithmetic.add.AddConstantToImageInPlace(net.imglib2.IterableRealInterval<capture of ?> image, capture of ? value)
	[0.0] (net.imglib2.IterableInterval<capture of ?> a) = net.imagej.ops.arithmetic.add.AddRandomAccessibleIntervalToIterableInterval(net.imglib2.IterableInterval<capture of ?> a, net.imglib2.RandomAccessibleInterval<capture of ?> b)
	[0.0] (net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image) = net.imagej.ops.arithmetic.add.AddConstantToPlanarDoubleImage(net.imglib2.img.planar.PlanarImg<net.imglib2.type.numeric.real.DoubleType, net.imglib2.img.basictypeaccess.array.DoubleArray> image, double value)
	[-100.0] (capture of ? out?) = net.imagej.ops.arithmetic.add.AddConstantToNumericType(capture of ? out?, capture of ? in, capture of ? value)
	[-10000.0] (net.imglib2.RandomAccessibleInterval<capture of ?> out) = net.imagej.ops.arithmetic.add.AddConstantToImageFunctional(net.imglib2.RandomAccessibleInterval<capture of ?> out, net.imglib2.IterableInterval<capture of ?> in, capture of ? value)
[INFO] What is 2 + 5? 7.0
Exception in thread "main" java.lang.IllegalArgumentException: No candidate 'createImg' ops
	at net.imagej.ops.DefaultOpMatchingService.findModule(DefaultOpMatchingService.java:93)
	at net.imagej.ops.DefaultOpService.module(DefaultOpService.java:110)
	at net.imagej.ops.DefaultOpService.run(DefaultOpService.java:77)
	at net.imagej.ops.DefaultOpService.create(DefaultOpService.java:391)
	at UsingOps.main(UsingOps.java:33)
```

Maybe this should be tested as part of a unit test, what with the `README` suggesting to use `createImg` and all...

### CODE REVIEW

**Comment by ctrueden** [comment]
Thanks @dscho!

It looks like we already fixed the [UsingOps](https://github.com/imagej/imagej-tutorials/blob/9f7e9ce3d4eeffb3462a99806bb4cb39019d595c/using-ops/src/main/java/UsingOps.java) example (upon which the README was based) to use `create` instead.

See also #69.

**Comment by dscho** [comment]
> It looks like we already fixed the UsingOps example (upon which the README was based) to use create instead.

I am afraid that `create` is deprecated...: https://github.com/imagej/imagej-ops/blob/ecea1714721bbd24e28487120e9a48ff7e312924/src/main/java/net/imagej/ops/DefaultOpService.java#L388-L392

**Comment by dscho** [comment]
BTW I am not really proud of this change: https://github.com/imagej/imagej-ops/pull/88/files#diff-04c6e90faac2675aa89e2176d2eec7d8R46. It really flies in the face of the goal to make OPS easy to use if the user already has to deal with image factories and types just to create an image – the first thing they would try to do! Further, there seems to be a usability issue with the Op selection, still: at first, I fixed the example to comply with `CreateImgNative`'s demand that the dimensions be given as a `net.imglib2.Dimensions` instance, but `CreateImgDefault` was picked and complained rightfully that `FinalDimensions` could not be mapped to `long[]`... It should not have been picked, then, though...

**Comment by ctrueden** [comment]
> I am afraid that `create` is deprecated

Right, I forgot, it was the other way around I guess. We must _not_ have updated the `UsingOps` example then...

> the user already has to deal with image factories and types just to create an image

I very much agree that we should avoid the need to pass such things as arguments. It's fine if there are signatures for it, but the simplest signature needs to do something sensible by default. And it should certainly not be the case that the README uses those signatures.

> complained rightfully that `FinalDimensions` could not be mapped to `long[]`

Right, we really need to complete #54.

> It should not have been picked, then

Agreed; will have to investigate that.

**Comment by dscho** [comment]
@ctrueden so... what about merging this branch, fixing the example in the README in Fiji?

**Comment by ctrueden** [comment]
There must be a way to fix this without importing an `ImageFactory` class. The title of this PR says it will fix the README "once and for all", but we certainly don't want to have this ugly reference in the README "once and for all"...

**Comment by dscho** [comment]
The problem this PR tries to address is that the example from the README *won't work*. It does *not* try to fix the ugliness that has been introduced while breaking that example.

I am sympathetic with your goal to fix the ugliness, but I disagree that it should hold up this bug fix even further.

**Comment by ctrueden** [comment]
What I don't want is to post code that will potentially be copy-paste replicated many times. If we introduce that ugliness to master, it will ripple outward, and hence take a long time for it to "fade away."

I do agree that leaving the README broken is terrible. So I will spend some time now investigating this issue and coming up with a proper fix. It will be one less thing to solve at the hackathon, then.

**Comment by dietzc** [comment]
maybe, as I already told you @dscho in person, it makes sense to wait until https://github.com/imagej/imagej-ops/pull/48 has been merged? I think @bnorthan addresses some of the issues by implementing various new CreateImage Ops.

**Comment by dscho** [comment]
> as I already told you @dscho in person, it makes sense to wait until #48 has been merged?

@dietzc sure. It would have been good to know about such intentional delays *before* I gave two presentations on *ImageJ OPS*, though. That way, I could have possibly held off and avoided disappointing people with yet another project that promises a lot but fulfills little (I am talking about impressions here, not facts, but in the long run impressions count more, as you well know).

**Comment by ctrueden** [comment]
@dscho I'm on it; we'll have the readme working before the end of the day.

**Comment by bnorthan** [comment]
@ctrueden, @dscho, @dietzc 

Yes Christian and I have been discussing the createImg issue in the port_kernels pull request https://github.com/imagej/imagej-ops/pull/48.

We have some ideas, more review and input is welcome, maybe at the Hackathon??  I can't make it but maybe I can follow some of the discussions on Skype??

The 'createImg' part of the Readme works with that pull request... however the equation part is really slow.  I'm not sure why.  It eventually finishes.

But then it fails when trying to add a constant.  The AddConstantToPlanarDoubleImage op seems to be run even though the input is a 'FloatType' image.

**Comment by ctrueden** [comment]
OK, I have this sorted out. My commit to fix the README behavior is: 41ffba8757f1bdc87e2ed6579b59057cde64b7c2.

This "does the right thing" by adding a createimg signature that takes only a `long[] dims`, so that the README stays simple and keeps working as is. Then we no longer need that factory complexity.

Thanks @dscho for that awesome unit test. It indeed fails without 41ffba8757f1bdc87e2ed6579b59057cde64b7c2, and passes with it. BTW, I also fixed up the `DefaultOpService` to use the name constants, and cleaned up the discrepancy between those built-in signatures and the built-ins listed in the `net.imagej.ops.Ops` class. And downcased `createImg` everywhere, as it should have been.

**Comment by ctrueden** [comment]
The `CreateImg` implementations will need further improvement in the future. In particular, we do not want to hardcode `ArrayImg` for all possible `long[]` dimensions, but rather use a heuristic like how SCIFIO does now. But that is a problem for later (hackathon or otherwise).

**Comment by dscho** [comment]
Thanks.

**Pull request merged**
