### PR TITLE
Bugfix in CentroidPolygon op

### PR DESCRIPTION
**Pull request by haesleinhuepf**
Hi guys,

i maybe found a bug in CentroidPolygon. I reported the bug on the forum:
http://forum.imagej.net/t/issue-with-polygons-in-ops/2227/7

The issue was: In CentroidPolygon.java, the stopping criterion of a loop was wrong. After fixing this, an index needs to be changed a bit as well. Now indexes and for-loop-stop-criterion are identical in CentroidPolygon and DefaultSizePolygon. In the same way, formulas are given on wikipedia:

https://en.wikipedia.org/wiki/Centroid#Centroid_of_polygon

So, I guess this was really a bug...

Furthermore, I removed an unnneccesary modulo operation from DefaultSizePolygon.

Cheers,
Robert

### CODE REVIEW

**Comment by dietzc** [comment]
@tibuch can you review?

**Comment by tibuch** [comment]
@dietzc the calculation of the centroid was wrong. This will fix the bug.
@haesleinhuepf thank you!

**Comment by dietzc** [comment]
tests passing?

**Comment by imagejan** [comment]
@haesleinhuepf you might want to adjust your author information (from `rhaase` to `haesleinhuepf`) so that your account is correctly shown on github?

**Comment by tibuch** [comment]
I can't find any centroid tests.

**Comment by haesleinhuepf** [comment]
I just commited a similar (but different) fix regardin the centroid of meshes. Review it carefully, as it may influence other Ops using the marching cubes implementation...

**Comment by dietzc** [comment]
> I can't find any centroid tests. 

we should add some.

**Comment by tibuch** [comment]
> Review it carefully

I checked the triangles table from http://paulbourke.net/geometry/polygonise/ and it looks like the triangles are stored in clockwise order. Inverting the insertion order should fix the problem.

@kephale could you doublecheck?

**Comment by dietzc** [comment]
after @kephale double-checked the mesh part, I'm happy to merge.

**Comment by kephale** [comment]
@dietzc looked it over, and tested it out in ThreeDViewer. Seems good to me.

**Comment by ctrueden** [comment]
Agh, build broken! Related tests are now failing:
```
Failed tests: 
  GeomTest.testBoundaryPixelCountConvexHull:296 geom.boundaryPixelCountConvexHull expected:<177.0> but was:<179.0>
  GeomTest.testCentroidMesh:218 expected:<-12.237808234> but was:<12.237808234514777>
```

**Pull request merged**
