### PR TITLE
Optimise BoxCount further

### PR DESCRIPTION
**Pull request by rimadoma**
Further optimises ops related to issue https://github.com/bonej-org/BoneJ2/issues/196

Changes execution times for a 256 x 256 x 256 binary image:
* BoxCount _25 s -> 1.1 s_ (Paremeters: maxSize 256, minSize 1, scaling 2.0) 
* Outline _2 s -> 500 ms_

### CODE REVIEW

**Comment by rimadoma** [comment]
@gselzer @ctrueden This PR can wait. I'll let you know when "my people" are happy with the performance. Apologies for not mentioning this earlier, and creating extra work.

**Comment by mdoube** [comment]
> when "my people" are happy with the performance

Looks like a major improvement. "This person" is happy with it.

**Comment by rimadoma** [comment]
OK, this PR is go then. @ctrueden It'd be rad if you had the time to cut a new release of `imagej-ops` for `pom-scijava:29.x.x` but no worries.

**Comment by ctrueden** [comment]
I tried to release a new imagej-ops, but Travis CI sees three new test failures:
```
-------------------------------------------------------------------------------
Test set: net.imagej.ops.morphology.outline.OutlineTest
-------------------------------------------------------------------------------
Tests run: 8, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.34 s <<< FAILURE! - in net.imagej.ops.morphology.outline.OutlineTest
testEdgeSquareExcludeEdgesFalse(net.imagej.ops.morphology.outline.OutlineTest)  Time elapsed: 0.046 s  <<< FAILURE!
java.lang.AssertionError: Wrong number of foreground elements in interval expected:<8> but was:<6>
        at net.imagej.ops.morphology.outline.OutlineTest.testEdgeSquareExcludeEdgesFalse(OutlineTest.java:206)

testOutlineSquare(net.imagej.ops.morphology.outline.OutlineTest)  Time elapsed: 0.039 s  <<< FAILURE!
java.lang.AssertionError: Wrong number of foreground elements in interval expected:<8> but was:<5>
        at net.imagej.ops.morphology.outline.OutlineTest.testOutlineSquare(OutlineTest.java:148)

testEdgeSquare(net.imagej.ops.morphology.outline.OutlineTest)  Time elapsed: 0.042 s  <<< FAILURE!
java.lang.AssertionError: Wrong number of foreground elements in interval expected:<7> but was:<5>
        at net.imagej.ops.morphology.outline.OutlineTest.testEdgeSquare(OutlineTest.java:177)
```
I reproduced them on a local Ubuntu box, but cannot reproduce on macOS.

@rimadoma Any thoughts?

**Comment by rimadoma** [comment]
@ctrueden Unable to reproduce on my Win10 laptop. I thought it might be the different number cores available, so I ran the tests repeatedly with `Executors.newFixedThreadPool(1..15)` (my laptop has 8 cores). They pass. Do to tests still fail if you revert to https://github.com/imagej/imagej-ops/pull/618/commits/365d628b0aba44d28f33777d23e6c37ce1f61560?

**Comment by rimadoma** [comment]
@ctrueden One more thought: is Maven on the Linux box configured to run tests in parallel?

**Comment by rimadoma** [comment]
I added a [commit](https://github.com/imagej/imagej-ops/commit/95b372756e864a4b53383cbf449d68ec1c187369) that uses `ThreadService` instead of its own `ExecutorService`. If that makes any difference, I'll add a similar fix for `BoxCount` to be on the safe side.

**Pull request merged**
