### PR TITLE
implement MinMax as FunctionOp

### PR DESCRIPTION
**Pull request by dietzc**
see above.

### CODE REVIEW

**Comment by dietzc** [comment]
I'd love I would be a cool kid, too. But I somehow can't.

**Comment by ctrueden** [comment]
Awesome! I just posted that one nitpick about imports. Otherwise looking great!

**Comment by dietzc** [comment]
I think there is still a bug in Mars that prevents the Formatter to work well.

**Comment by ctrueden** [comment]
Yeah, I heard about that, so I am sticking with Luna for now.

**Comment by dietzc** [comment]
I should do that, too. I will quickly format everything

**Comment by dietzc** [comment]
better?

**Comment by ctrueden** [comment]
:+1:

**Pull request merged**
