### PR TITLE
Use platform independent string

### PR DESCRIPTION
**Pull request by jaywarrick**
Test used "```python\n" which fails on Windows given Windows equivalent is "```python\r\n". Now using String.format and %n for platform independent newline character

### CODE REVIEW

**Comment by jaywarrick** [comment]
Sorry for the weird commit history. I couldn't seem to get them merged into a single commit so that there is no history of a failing build. This is trying to fix botched PR https://github.com/imagej/imagej-ops/pull/268

**Comment by imagejan** [comment]
This was fixed a while ago and should be on master already: see https://github.com/imagej/imagej-ops/commit/13861a5

**Comment by ctrueden** [comment]
Thanks for pointing that out, @imagejan.

**Comment by jaywarrick** [comment]
Sorry all. I have no idea how I had out of date code. I just cloned it yesterday directly from the main repo onto an absolutely brand new computer that has never seen the repo before. I was getting it set up for future programming against new imagej-ops capabilities. Very mysterious to me. How would it let me commit something that didn't need changing? Sorry about that. Thanks for catching this.

Best,

Jay

On Oct 20, 2015, at 8:10 AM, Curtis Rueden <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #269<https://github.com/imagej/imagej-ops/pull/269>.

**Comment by imagejan** [comment]
> I just cloned it yesterday directly from the main repo onto an absolutely brand new computer that has never seen the repo before.

Seems like you cloned from your own out-of-date fork (https://github.com/jaywarrick/imagej-ops) instead of the main repository (https://github.com/imagej/imagej-ops).
To [sync your fork](https://help.github.com/articles/syncing-a-fork/), you can pull from the upstream repo and merge (or force-push to your fork):
 - `git fetch upstream`
 - `git checkout master`
 - `git merge upstream/master`

**Comment by jaywarrick** [comment]
Ahhhhh! Wow. I even specifically went to the github site directly to imagej/imagej-ops instead of jaywarrick/imagej-ops and chose to clone in desktop (I'm lame and use the github desktop app). I wonder if it new I had forked it before so did that one instead?... Oh well.

Thanks for figuring it out so I can be more careful of that type of mixup in the future.

Best,

Jay

On Oct 20, 2015, at 3:10 PM, Jan Eglinger <notifications@github.com<mailto:notifications@github.com>> wrote:


I just cloned it yesterday directly from the main repo onto an absolutely brand new computer that has never seen the repo before.

Seems like you cloned from your own out-of-date fork (https://github.com/jaywarrick/imagej-ops) instead of the main repository (https://github.com/imagej/imagej-ops).
To sync your fork<https://help.github.com/articles/syncing-a-fork/>, you can pull from the upstream repo and merge (or force-push to your fork):

  *   git fetch upstream
  *   git checkout master
  *   git merge upstream/master

**Pull request closed without merging**
