### PR TITLE
Real binary math

### PR DESCRIPTION
**Pull request by apal4**
Tests for RealBinaryMath now generated- ComplexBitType is still separate

### CODE REVIEW

**Comment by ctrueden** [comment]
I cleaned up this branch. It is looking pretty good now, but still needs more thorough review. In my initial investigation, I noticed that it causes another preexisting test (`AddConstantToNumericTypeTest`) now fails. Will try to dig further next week.

**Comment by hinerm** [comment]
@ctrueden test fails because `RealBinaryMath#RealTypeAdd` is also matching the use case in this test, and takes priority since `AddConstantToNumericType` is low priority.

**Comment by hinerm** [comment]
To fix we just have to update the numeric type tests to use types that are `NumericType` and are not also `RealType`.

**Comment by hinerm** [comment]
fixed in https://github.com/imagej/imagej-ops/commit/6357b651faa934426d73bb26df061a4c05d7d3a2. Squash if you want @ctrueden

**Comment by ctrueden** [comment]
Thanks @hinerm!

**Pull request merged**
