### PR TITLE
Haralick features

### PR DESCRIPTION
**Pull request by angrauma**
add 3d haralick features and modify 2d haralick features

### CODE REVIEW

**Comment by dietzc** [comment]
@DanielSeebacher can you do the review?

**Comment by angrauma** [comment]
I tested the haralick features against matlab with a non quadratic image on my local computer. 
Just to make sure it also works for non quadratic images. Because I forgot to change the values back to the quadratic image we use to test all our features, i had to change it now.

**Comment by dietzc** [comment]
@DanielSeebacher can you review and merge?

**Comment by dietzc** [comment]
@angrauma @DanielSeebacher I'd love to merge this PR into output-ops.

**Pull request merged**
