### PR TITLE
Create Conditional Op

### PR DESCRIPTION
**Pull request by LeonYang5114**
This Op works as a conditional operator. 

Not sure do we have other Ops that do the same thing, but since this is quick to implement, I just code it up to make things go faster if we really need it.

Also I don't think that the name is good, but for now I cannot come up with a better one. Please nitpick :-)

### CODE REVIEW

**Comment by ctrueden** [comment]
It seems like this op should be named `if`. The class you created might be `IfBoolType`. The `trueValue` and `falseValue` need to be parameters to the op, and there should be no public constructor. And it needs a `@Plugin(type = Ops.If.class)` annotation.

Should there be another class `IfCondition` that takes a `Condition<T>` as input instead of a `BoolType`? Or is that overcomplicating things?

We should also decide whether to type the boolean one on `BoolType` or `Boolean`. Since it's the input, the object does not need to be mutable, so `Boolean` would be OK and not require the ImgLib2 library—hence allowing it to be later moved to a more general `scijava-ops` layer at a future point. And we have (or will have) a SciJava `Converter` implementation to go from `BoolType` to `Boolean`, so we won't have to create the `BoolType` version separately.

@dietzc Does this all make sense?

**Comment by dietzc** [comment]
it does. I just try to find an use-case for this `Op`? Not saying I don't like it. I just don't understand it :-)

**Comment by ctrueden** [comment]
@dietzc At the very least, so you can write `if(condition, t, f)` statements as part of an `eval`?

**Comment by dietzc** [comment]
Which absolutely makes sense. Didn't think about `eval` at all. Thanks @ctrueden !

**Comment by LeonYang5114** [comment]
@ctrueden @dietzc I came up with this Op when I was working on the NanBackground class. With this Op and a Map, we can modify an Image given its threshold output. 
Using Boolean as input type definitely make sense to me. And with the IfCondition, we can do some simple thresholding + modification in just one Map call. That might also be convenient.

**Comment by LeonYang5114** [comment]
@ctrueden Java does not allow "if" as a package name, so I put the IfBoolean and IfCondition in a package called "conditional." Other things are just as you specified. Is there anything I should change?

**Comment by LeonYang5114** [comment]
A more up-to-date and cleaner branch is created. This branch is now closed.

**Pull request closed without merging**
