### PR TITLE
New convolution kernels with Gabor, BiGauss and 2nd derivative BiGauss

### PR DESCRIPTION
**Pull request by xulman**
Hi,
I propose to add $SUBJ as a new ops, as a part of my larger effort to include implementation of two papers on curvilinear structures detection.

Accidentally, it goes in the direction of issue #325.

BTW: Do we have anywhere docs for the OpMethod annotation? Also some tutorial on the plugin system in general could help, to help me understand/confirm why there should (must?) be the non-generic plugin wrappers (Create*.java)... yes, I'm newbie for imagej-ops, Fiji, Java.

How do I populate imagej-ops/target/generated-sources/from-template/net/imagej/ops/Ops.java automatically?

Cheers,
Vladimir @de.NBI @Tomancak lab @mpi-cbg.de

### CODE REVIEW

**Comment by ctrueden** [comment]
@xulman Cool!

> Do we have anywhere docs for the OpMethod annotation?

Only all the places it is used in all the namespace classes. And perhaps more helpfully, the [unit test that uses them](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.36.0/src/test/java/net/imagej/ops/AbstractNamespaceTest.java#L83-L118).

> Also some tutorial on the plugin system in general could help, to help me understand/confirm why there should (must?) be the non-generic plugin wrappers (Create*.java)

Did you have a look [here](https://github.com/imagej/tutorials)? Or for the bleeding edge, at [these Beaker notebooks](https://github.com/imagej/tutorials/tree/dev-manual/ImageJ_Notebooks)?

> How do I populate imagej-ops/target/generated-sources/from-template/net/imagej/ops/Ops.java automatically?

You hack the [Ops.list](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.36.0/src/main/templates/net/imagej/ops/Ops.list) template.

**Comment by xulman** [comment]
Thanks so much for the resources. I've studied some of them recently and now again. I'll have a look on the Beaker notebooks now.


As for the OpMethod, so its purpose is to explain what plugin the type-safe ops-namespace function [e.g. kernelGabor_float()](https://github.com/xulman/imagej-ops/blob/Ulman-AddingGaborAndBiGaussKernels/src/main/java/net/imagej/ops/create/CreateNamespace.java#L649) was intended to match?

> Not sure what you mean by non-generic plugin wrappers, though. You mean e.g. Ops.Math.Add.class? This helps with fast lookup of all math.add ops, for the op matcher.

I created [a generics plugin](https://github.com/xulman/imagej-ops/blob/Ulman-AddingGaborAndBiGaussKernels/src/main/java/net/imagej/ops/create/kernelGabor/DefaultCreateKernelGabor.java). Then, according to kernelGauss plugin that I used as a template, I created, e.g., [this non-generics plugin](https://github.com/xulman/imagej-ops/blob/Ulman-AddingGaborAndBiGaussKernels/src/main/java/net/imagej/ops/create/kernelGabor/CreateKernelGaborFloatType.java). This I meant with ''non-generics'' plugin. Is the purpose of these only to have:
* A types-aware implementation of the plugin in the P-code (compiled), which, as a matter of fact, in the end only calls the type-not-aware, originally generics-based plugin?
* An explicit plugin with the particular combination of parameter types that client-code can reference, and somebody else can replace/override with her implementation?

> You hack the Ops.list template.

Yes, but what has to be triggered afterwards to propagate the change into the Ops.java?

Sorry for a another set of questions.
V.

**Comment by ctrueden** [comment]
Sorry for the long delay in reply, @xulman.

> what has to be triggered afterwards to propagate the change into the Ops.java?

It happens as part of Maven's `generate-sources` phase of the build lifecycle. In Eclipse, you need to "Update Maven Project" in order to redo that step, unfortunately. From the command line, it always happens as a precursor to `compile` (or `package` or `install`).

> Is the purpose of these only to have:

The purpose of the `FloatType`-specific method here is to provide a simpler method signature with sensible defaults, and correspondingly correct output types.

Does it make sense? Perhaps we can chat in detail in person during the upcoming Learnathon?

**Comment by ctrueden** [comment]
It seems this PR currently has failing tests:
```
Running net.imagej.ops.create.CreateNamespaceTest
[ERROR] Mismatched inputs:
	op = net.imagej.ops.create.kernelBiGauss.DefaultCreateKernel2ndDerivBiGauss
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.create.CreateNamespace.kernel2ndDerivBiGauss(double[],int,net.imglib2.type.numeric.ComplexType)
[ERROR] Mismatched inputs:
	op = net.imagej.ops.create.kernelBiGauss.CreateKernel2ndDerivBiGaussDoubleType
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.create.CreateNamespace.kernel2ndDerivBiGauss(double[],int)
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelBiGauss.CreateKernel2ndDerivBiGaussDoubleType.class)
	public RandomAccessibleInterval kernel2ndDerivBiGauss(final double[] in1, final Integer in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelBiGauss.CreateKernel2ndDerivBiGaussDoubleType.class, in1, in2);
		return result;
	}

	@OpMethod(op = net.imagej.ops.create.kernelBiGauss.DefaultCreateKernel2ndDerivBiGauss.class)
	public RandomAccessibleInterval kernel2ndDerivBiGauss(final double[] in1, final Integer in2, final ComplexType typeVar) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelBiGauss.DefaultCreateKernel2ndDerivBiGauss.class, in1, in2, typeVar);
		return result;
	}
[ERROR] Mismatched inputs:
	op = net.imagej.ops.create.kernelBiGauss.DefaultCreateKernelBiGauss
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.create.CreateNamespace.kernelBiGauss(double[],int,net.imglib2.type.numeric.ComplexType)
[ERROR] Mismatched inputs:
	op = net.imagej.ops.create.kernelBiGauss.CreateKernelBiGaussDoubleType
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.create.CreateNamespace.kernelBiGauss(double[],int)
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelBiGauss.CreateKernelBiGaussDoubleType.class)
	public RandomAccessibleInterval kernelBiGauss(final double[] in1, final Integer in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelBiGauss.CreateKernelBiGaussDoubleType.class, in1, in2);
		return result;
	}

	@OpMethod(op = net.imagej.ops.create.kernelBiGauss.DefaultCreateKernelBiGauss.class)
	public RandomAccessibleInterval kernelBiGauss(final double[] in1, final Integer in2, final ComplexType typeVar) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelBiGauss.DefaultCreateKernelBiGauss.class, in1, in2, typeVar);
		return result;
	}
[ERROR] Mismatched inputs:
	op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropic
	method = public net.imglib2.RandomAccessibleInterval net.imagej.ops.create.CreateNamespace.kernelGabor(double,double[],net.imglib2.type.numeric.ComplexType)
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropic.class)
	public RandomAccessibleInterval kernelGabor(final Double in1, final double[] in2, final ComplexType typeVar) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropic.class, in1, in2, typeVar);
		return result;
	}
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.035 sec <<< FAILURE! - in net.imagej.ops.create.CreateNamespaceTest
testCompleteness(net.imagej.ops.create.CreateNamespaceTest)  Time elapsed: 0.035 sec  <<< FAILURE!
java.lang.AssertionError: Coverage mismatch
	at net.imagej.ops.create.CreateNamespaceTest.testCompleteness(CreateNamespaceTest.java:51)
```
and
```
Running net.imagej.ops.GlobalNamespaceTest
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborComplexDoubleType.class)
	public RandomAccessibleInterval GaborComplexDouble(final double[] in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborComplexDoubleType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborComplexFloatType.class)
	public RandomAccessibleInterval GaborComplexFloat(final double[] in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborComplexFloatType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborDoubleType.class)
	public RandomAccessibleInterval GaborDouble(final double[] in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborDoubleType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborFloatType.class)
	public RandomAccessibleInterval GaborFloat(final double[] in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborFloatType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicComplexDoubleType.class)
	public RandomAccessibleInterval IsotropicGaborComplexDouble(final Double in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicComplexDoubleType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicComplexFloatType.class)
	public RandomAccessibleInterval IsotropicGaborComplexFloat(final Double in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicComplexFloatType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicDoubleType.class)
	public RandomAccessibleInterval IsotropicGaborDouble(final Double in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicDoubleType.class, in1, in2);
		return result;
	}
[ERROR] Missing methods:

	@OpMethod(op = net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicFloatType.class)
	public RandomAccessibleInterval IsotropicGaborFloat(final Double in1, final double[] in2) {
		final RandomAccessibleInterval result =
			(RandomAccessibleInterval) ops().run(net.imagej.ops.create.kernelGabor.CreateKernelGaborIsotropicFloatType.class, in1, in2);
		return result;
	}
```

@xulman When you get a chance, please update it. Or you could wait till the Learnathon and we can work on this together. Eventually, I am going to rework the namespaces a bit to avoid this rigamarole. But it requires better generic type matching first.

**Comment by xulman** [comment]
Hi @ctrueden,
I fixed (I hope) the coverage mismatches (which stemmed from my misunderstanding) and pushed it to this branch. Also, I have removed underscores '_' from function names to make Codacy a bit happier.

Vlado

PS: Sorry for no replies for a long time, your
>  I am going to rework the namespaces a bit...
chilled out my enthusiasm for working on new ops for a while, but it's certainly better now again  :-)

**Comment by xulman** [comment]
Hi again,
I've stripped away the Float versions of the Gabor kernel (as they have the same input parameter types as the still-present Double versions of the kernels, the difference is only in the output type).

Test's now, however, produce one warning regarding exception risen during the plug-in discovery -- I'm, with my _current_ abilities not yet able to discover what went wrong, and why... But the test does not fail.

Vlado

**Comment by xulman** [comment]
Hi @ctrueden,
I've finally resolved ops coverage issues and all tests go green now.
Codacy keeps complaining about 'Package name contains upper case characters' but I don't know how to work around as camelCase (used in the folder names) seems to be the cause, while it is used elsewhere in the ops source tree.

Holding on in this project now, waiting for your inputs... (take your time, this one is not in hurry)

Cheers,
Vlado

**Comment by imagejan** [comment]
@xulman wrote:
> Codacy keeps complaining about 'Package name contains upper case characters' but I don't know how to work around as camelCase (used in the folder names) seems to be the cause, while it is used elsewhere in the ops source tree.

Don't worry, you can safely ignore the Codacy check. It is unfortunate that codacy was enabled temporarily when this PR was created, and now the github hook still sticks around. (New PRs will not have a codacy check currently.)

If/when we choose to re-activate codacy hooks at some point, we'll have to configure the rules to allow certain code patterns such as this deliberate camelCase naming...

**Comment by xulman** [comment]
@imagejan, thank you for the explanation, cheers

**Comment by ctrueden** [comment]
Really sorry that this slipped through the cracks for so long. Thanks so much for your efforts on it. :beers:

**Pull request merged**
