### PR TITLE
Add new Create Op to create Imgs from Imgs

### PR DESCRIPTION
**Pull request by dietzc**
This `Op` creates an `Img` given the information from another `Img`.

### CODE REVIEW

**Comment by hinerm** [comment]
I am confused.. `Img` has a [`copy`](https://github.com/imglib/imglib2/blob/imglib2-2.3.0/src/main/java/net/imglib2/img/Img.java#L70) method... why is that not sufficient..?

**Comment by dietzc** [comment]
`copy()` copies the `Img` (including the content). Creating a new empty `Img` is something else.

**Comment by hinerm** [comment]
ah, I saw "given the information" and assumed it was copying data too.

OK, so the set of Ops that performed this behavior before was deleted in https://github.com/imagej/imagej-ops/commit/bf3dafe6e6010525a9ef6573c025ff93996dabbf. Was that removal a mistake?

More to the point, why do we need a 1-liner op that delegates to a different op?

**Comment by dietzc** [comment]
Deleting the previous `Op` was not a mistake as this `Op` was using an entirely different infrastructure. We just didn't re-add this short-cut again. 

> More to the point, why do we need a 1-liner op that delegates to a different op?

Because it's more convenient than writing `ops.create(img, img.firstElement().createVariable(), img.factory())`.

**Comment by hinerm** [comment]
>ops.create(img, img.firstElement().createVariable(), img.factory())

So without this `Op`, you could call `ops.create(img)` and right now it looks like the limitation is that it will give you a `DoubleType` `Img` back because it always forces the resulting `Img` to match the type of `CreateNativeType`.

Philosophically, my take is that optional parameters are used in [DefaultCreateImg](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.14.0/src/main/java/net/imagej/ops/create/DefaultCreateImg.java#L71-L75) so that a single `Op` can encapsulate the functionality of the various `Img` creation method signatures and pathways.

So instead of adding a delegating op for this one use case, why not add the logic to `DefaultCreateImg` so that if its input is typed, that type can be reused instead of falling back to the default `NativeType`?

Sorry if you and @ctrueden already discussed guidelines for when to use optional params or conditional logic and when to create helper ops... it's not completely clear to me which option is more in line with the ops goals.

**Comment by hinerm** [comment]
Another possibility would be to give the `CreateNativeType` an optional parameter.. if that param is something with a type, it returns that type, and if not returns `DoubleType`..

**Comment by ctrueden** [comment]
I think that optional args vs. multiple ops must be weighed case by case. Certainly there are limitations on which situations can properly cover optional args. I would also not use optional args for mutually exclusive params—e.g., if you can say either `foo(a, c)` _or_ `foo(a, b)` but writing `foo(a, b, c)` would make no sense, then I would rather have `FooA` and `FooB` ops than a single `Foo` with `b` and `c` being optional.

In this case, I think having a single op that takes an optional output type argument is totally fair, and likely simpler than two op classes.

@hinerm One quick point about your earlier question regarding why `copy()` might not be sufficient: even if there is a single method call that does a thing to an object, we still might want to wrap it in an op so that that op is available as a function in contexts such as the op expression evaluator. As long as the `copy()` method is deterministic, it is potentially handy to wrap it as an op. We are planning to wrap lots of lower level ImgLib2 functionality in this way too (e.g., `Views`), for similar reasons.

**Comment by dietzc** [comment]
> In this case, I think having a single op that takes optional output type and factory arguments is totally fair, and likely simpler than two op classes. Would you agree, @dietzc?

I don't understand what you are suggesting :-) We have an `Op` with two optional input parameters, however I still need the second `Op` which makes it easier to create `img`s from `Img`s?

One comment about case-logic and several `Op`s: I have also not really an idea what is better when and I really think we have to judge from case to case. However, case-logic is not easily extensible, especially in this case as we don't have an interface we could use (like `IsTyped`) and we would have to cover several cases (e.g. `IterableInterval`, `RandomAccessibleInterval`) and we don't know which implementations of `Dimension` will hold a `Type` in the future.

**Comment by ctrueden** [comment]
> I don't understand what you are suggesting :-) We have an `Op` with two optional input parameters, however I still need the second `Op` which makes it easier to create `img`s from `Img`s?

Right, sorry, I need to read the code more carefully next time before spouting off.

So, OK, I think what this is doing is good! The only concern I have is the unsafe cast to `Img<T>`—the `CreateImg` implementation chosen might not produce anything of that type. In practice, you are implicitly relying on the fact that `DefaultCreateImg` will be chosen; maybe it would be better to just invoke that implementation directly using `DefaultCreateImg.class`. Or even skipping the ops framework altogether and calling a plain old Java method instead of `ops.run`.

**Comment by dietzc** [comment]
@ctrueden what about typing CreateImg as an OutputOp>?

**Comment by ctrueden** [comment]
@dietzc Even then someone could implement `CreateImg` but define a second output parameter and then the `ops.run` call would give back a `List` instead of an `Img<T>`.

**Comment by dietzc** [comment]
Ok. The `Op` now uses `DefaultCreateImg`.

**Comment by ctrueden** [comment]
Good enough for government work! :+1:

**Comment by dietzc** [comment]
:+1:

**Pull request merged**
